<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
	  <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>GCaLink</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseRidGraph>true</UseRidGraph>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ViewModels\**" />
    <Compile Remove="Views\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="ViewModels\**" />
    <None Remove="Views\**" />
    <Page Remove="ViewModels\**" />
    <Page Remove="Views\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Assets\google-si-dark.png" />
    <Content Remove="Assets\google-si-light.png" />
    <Content Remove="Assets\google-si-neutral.png" />
  </ItemGroup>
  <ItemGroup>
  <Compile Update="ViewWindows\WidgetView\WidgetWindow.xaml.cs">
		<DependentUpon>WidgetWindow.xaml</DependentUpon>
	</Compile>
  <Compile Update="ViewWindows\SettingsView\SettingsWindow.xaml.cs">
		<DependentUpon>SettingsWindow.xaml</DependentUpon>
	</Compile>
	<Compile Update="ViewWindows\DayView\DayViewWindow.xaml.cs">
		<DependentUpon>DayViewWindow.xaml</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.76.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.75.0.4206" />
    <PackageReference Include="Ical.Net" Version="5.2.3" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
  </ItemGroup>
  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Remove="Views\**" />
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="ViewModels\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ViewWindows\TodoView\" />
    <Folder Include="ViewWindows\WeekView\" />
  </ItemGroup>
</Project>